---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: defend-lumenia-network-policy
  namespace: lumenia
spec:
  podSelector:
    matchLabels:
      realm: lumenia
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector: {}
