---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lumenia-merchant-network-policy
  namespace: lumenia
spec:
  podSelector:
    matchLabels:
      role: merchant
  policyTypes:
    - Egress
  egress:
    - to:
      - namespaceSelector:
           matchLabels:
            kubernetes.io/metadata.name: wilderness
