---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: citizens
  namespace: lumenia
  labels:
    role: citizen
    realm: lumenia
spec:
  replicas: 2
  selector:
    matchLabels:
      role: citizen
      realm: lumenia
  template:
    metadata:
      labels:
        role: citizen
        realm: lumenia
    spec:
      containers:
      - name: citizen
        image: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scholars
  namespace: lumenia
  labels:
    role: scholar
    realm: lumenia
spec:
  replicas: 2
  selector:
    matchLabels:
      role: scholar
      realm: lumenia
  template:
    metadata:
      labels:
        role: scholar
        realm: lumenia
    spec:
      containers:
      - name: scholar
        image: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchants
  namespace: lumenia
  labels:
    role: merchant
    realm: lumenia
spec:
  replicas: 2
  selector:
    matchLabels:
      role: merchant
      realm: lumenia
  template:
    metadata:
      labels:
        role: merchant
        realm: lumenia
    spec:
      containers:
      - name: merchant
        image: nginx
