---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bonus-network-policy
  namespace: lumenia
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: umbra
      ports:
        - protocol: TCP
          port: 8080
